# Generated by Django 3.1.3 on 2020-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdemcoCode",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                    ("message_type", models.IntegerField(verbose_name="Тип")), ],
            options={"verbose_name": "Код", "verbose_name_plural": "Коды", },
        ),
        migrations.CreateModel(
            name="MessageETHContactID",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=128, verbose_name="Сообщение")),
                ("user", models.IntegerField(verbose_name="Номер пользователя")),
                ("uid", models.IntegerField(verbose_name="Идентификатор объекта")),
                ("object", models.IntegerField(verbose_name="Номер объекта")),
                ("type", models.IntegerField(verbose_name="Тип объекта")),
                ("code", models.IntegerField(verbose_name="Адемко Код")),
                ("section", models.IntegerField(verbose_name="Номер секции")),
                ("area", models.IntegerField(verbose_name="Номер зоны")),
                ("time_stamp", models.TimeField(verbose_name="Время")),
            ],
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения", },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object", models.IntegerField(verbose_name="Номер объекта")),
                ("name", models.CharField(max_length=128, verbose_name="Имя объекта")),
                ("enabled", models.BooleanField(verbose_name="Обслуживание")),
                ("lat", models.FloatField(verbose_name="Долгота")),
                ("lon", models.FloatField(verbose_name="Широта")),
                ("trek", models.IntegerField(verbose_name="Трек")),
                ("moved", models.BooleanField(verbose_name="Движимый")),
                ("connection_type", models.IntegerField(verbose_name="Тип соединения")),
                ("image_map", models.IntegerField(verbose_name="Номер изображения")),
            ],
            options={"verbose_name": "Объект", "verbose_name_plural": "Объекты", },
        ),
    ]
