name: Publish on Docker Hub and Deploy
on:
  release:
    types: [published]
jobs:
  analysis:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: docker://postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: cloud
  steps:
    - name: Git clone
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Pipenv for Github Actions
      uses: dschep/install-pipenv-action@v1
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Flake8
      uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
  build_and_pub:
    needs: [analysis]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        # Сначала мы логинимся в docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Git clone
        uses: actions/checkout@v2
      - name: Build image
        # Собираем image и называем его так как указано в hub.docker т.е. login/repository:version
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        # Пушим образ в registry
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}




